% 定义全局常数
global ELECTRON_EFFECTIVE_MASS BOLTZMANN_CONSTANT ELECTRON_CHARGE MOBILITY LATTICE_TEMPERATURE RELAXATION_PARAMETER THETA DIELECTRIC_PERMITTIVITY VOLTAGE_DROP;

% 为常数分配值，这里仅作展示，你需要替换为真实的值
ELECTRON_EFFECTIVE_MASS = 2.36834e-32; % in kg
BOLTZMANN_CONSTANT = 0.138e-4;
ELECTRON_CHARGE = 0.1602;
MOBILITY = 0.75; 
LATTICE_TEMPERATURE = 300; % in Kelvins
RELAXATION_PARAMETER = ELECTRON_EFFECTIVE_MASS * MOBILITY / ELECTRON_CHARGE; % defined as m*mu/e
THETA = BOLTZMANN_CONSTANT / ELECTRON_EFFECTIVE_MASS * LATTICE_TEMPERATURE; 
DIELECTRIC_PERMITTIVITY = 11.7 * 8.85418; % 
VOLTAGE_DROP = 1.5;
save('parameters.mat', 'ELECTRON_EFFECTIVE_MASS', 'BOLTZMANN_CONSTANT', 'ELECTRON_CHARGE', 'MOBILITY', 'LATTICE_TEMPERATURE', 'RELAXATION_PARAMETER', 'THETA', 'DIELECTRIC_PERMITTIVITY', 'VOLTAGE_DROP');
